# This is a basic workflow to help you get started with Actions

name: build_python_package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest      
    steps:
    #- name: Extract version string
    #  id: extract-version
    #  run: |
    #    version=$(echo ${{ github.event.release.tag_name }} | cut -c2-)
    #    echo "::set-output name=version::$version"
    - uses: actions/checkout@v2
    - name: Build manylinux python wheels
    #  env: 
    #    SGPP_VERSION: ${{steps.extract-version.outputs.version}}
      uses: ./.github/build_manylinux_package
    - name: post-build
    #  env: 
    #    SGPP_VERSION: ${{steps.extract-version.outputs.version}}
      run: |
        ls -la .
        ls -la ./dist
        ls -la ./wheelhouse
    #   echo $SGPP_VERSION
    - name: upload to testing pypi
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN_TEST }}
      run: |
        twine upload --repository testpypi wheelhouse/*-manylinux*.whl
