#          (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.1.zip","swigwin-4.0.1.zip");
name: windowsCI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install swig
        run: |
          dir "C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64"
          (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.1.zip","d:\a\_temp\swigwin-4.0.1.zip");
          Expand-Archive d:\a\_temp\swigwin-4.0.1.zip d:\a\_temp\;
      - uses: actions/checkout@v2
      - uses: numworks/setup-msys2@v1
        with:
          update: true
          path-type: inherit
      - name: install mingw
        run: |
          msys2do pacman -S --noconfirm mingw-w64-x86_64-toolchain
      - name: install scons
        run: python -m pip install scons pywin32
      - name: build
        run: |
          echo ::add-path::$RUNNER_TEMP/msys/msys64/mingw64/bin
          $Env:PATH="d:\a\_temp\swigwin-4.0.1;d:\a\_temp\msys\msys64\mingw64\bin;$Env:PATH"
          echo $Env:PATH
          swig -version
          scons -j2 PYDOC=0 CHECK_STYLE=0 COMPILER=gnu OPT=1 GSL_INCLUDE_PATH="" CPPDEFINES="_POSIX_C_SOURCE=1"
