name: windowsCI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: numworks/setup-msys2@v1
    - name: update msys2
      run:  msys2do pacman -Syu --noconfirm
    - name: install mingw
      run: msys2do pacman -S --noconfirm mingw-w64-x86_64-toolchain
    - name: add mingwpath
      run: echo "::add-path::msys/msys64/usr/bin"
    - name: install scons
      run: python -m pip install scons pywin32
    - name: build
      run: scons -j2 SG_ALL=0 SG_BASE=1 COMPILER=gnu
