#          (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.1.zip","swigwin-4.0.1.zip");
name: windowsCI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.7.7' 
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64' 
          # You can test your matrix by printing the current Python version
      - name: Copy Python to Python3.exe
        run: |
         Copy-Item "C:\hostedtoolcache\windows\Python\3.7.7\x64\python.exe" -Destination "C:\hostedtoolcache\windows\Python\3.7.7\x64\python3.exe"
         Copy-Item "C:\hostedtoolcache\windows\Boost\1.72.0\lib\boost_unit_test_framework-vc142-mt-x64-1_72.dll" -Destination "C:\hostedtoolcache\windows\Boost\1.72.0\lib\boost_unit_test_framework.dll"
#      - name: Remove choco gcc
#        run: |
#          choco uninstall mingw strawberryperl -y
#          Remove-Item -Recurse -Force C:\Strawberry
#          Remove-Item -Recurse -Force C:\ProgramData\Chocolatey
      - name: Install swig
        run: |
          Get-ChildItem -Path C:\hostedtoolcache\windows\Boost\1.72.0
          Get-ChildItem -Path C:\hostedtoolcache\windows\Boost\1.72.0\lib
          Copy-Item -Path "C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64" -Destination "d:\a\_temp\java" -Recurse
          (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.1.zip","d:\a\_temp\swigwin-4.0.1.zip");
          Expand-Archive d:\a\_temp\swigwin-4.0.1.zip d:\a\_temp\;
      - uses: actions/checkout@v2
#      - uses: eine/setup-msys2@v0
#        with:
#          update: true
#      - name: install mingw
#        run: |
#          msys2do pacman -Su
#          msys2do pacman -S --noconfirm mingw-w64-x86_64-toolchain
#          msys2do pacman -S --noconfirm mingw-w64-x86_64-python-numpy
      - name: add-path
        run: |
         c:\msys64\usr\bin\pacman.exe -S --noconfirm mingw-w64-x86_64-boost
         echo "::add-path::c:\msys64\mingw64\bin"
         echo "::add-path::c:\hostedtoolcache\windows\Python\3.7.7\x64"
      - name: build
        run: |
          Copy-Item "c:\msys64\mingw64\bin\libboost_unit_test_framework-mt.dll -Destination "c:\msys64\mingw64\bin\boost_unit_test_framework.dll"
          python -m pip install scons pywin32 numpy scipy matplotlib
          $Env:JAVA_HOME = "d:\a\_temp\java"
          echo "::add-path::C:/msys64/mingw64/bin"
          $Env:PATH="d:\a\_temp\swigwin-4.0.1;C:\msys64\mingw64\bin;$Env:PATH"
          echo $Env:PATH
          echo $Env:BOOST_ROOT_1_72_0
          swig -version
          scons -j2 PYDOC=0 CHECK_STYLE=0 COMPILER=gnu OPT=1 GSL_INCLUDE_PATH="" CPPDEFINES="_POSIX_C_SOURCE=1" CC="C:\msys64\mingw64\bin\gcc.exe" CXX="C:\msys64\mingw64\bin\g++.exe" LINK="C:\msys64\mingw64\bin\g++.exe" BOOST_INCLUDE_PATH="C:\msys64\mingw64\include" BOOST_LIBRARY_PATH="C:\msys64\mingw64\bin"
